// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "7eb93964-beff-40cc-9b5c-8f4908a601a7");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1549699434);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1549699554);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1550205883);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1549720914);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1549720794);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1549700004);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1549699794);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1549699674);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 716800);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.ctrlTab.migrated", true);
user_pref("browser.ctrlTab.recentlyUsedOrder", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1549699044);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{4c0e129f-3004-4366-ab0c-7a83aeea92d7}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1549641600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\",\"webcompat-reporter_mozilla_org\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1550205857833");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1550207659833");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1550205858898");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1550209458898");
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1550205855");
user_pref("browser.slowStartup.averageTime", 2067);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20190128144255");
user_pref("browser.startup.homepage_override.mstone", "65.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"feed-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1549699048336");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.performance.recording.interval", 1000);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "787aa1686e9841ad81d4dd8322f5fdfd");
user_pref("extensions.blocklist.lastModified", "Fri, 08 Feb 2019 12:03:20 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1549699438);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190128144255");
user_pref("extensions.lastAppVersion", "65.0");
user_pref("extensions.lastPlatformVersion", "65.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"388ddedf-bb7c-4a94-8383-c945823964b0\",\"screenshots@mozilla.org\":\"bc0737de-512a-475f-afbe-40db888dcb37\",\"formautofill@mozilla.org\":\"e33dff7a-5cbd-4108-9e5c-03a22f6bed71\",\"webcompat-reporter@mozilla.org\":\"5779916c-bd93-44ec-bd74-6298b3965f1c\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1549700633);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20190128144255");
user_pref("media.gmp-manager.lastCheck", 1549700162);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1549700633);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "03a65556-7e77-4049-819f-36b282ede229");
user_pref("security.sandbox.plugin.tempDirSuffix", "7ff0fc74-17c5-4fea-a428-d8c850fd3ff2");
user_pref("services.blocklist.addons.checked", 1549700004);
user_pref("services.blocklist.gfx.checked", 1549700004);
user_pref("services.blocklist.onecrl.checked", 1549700004);
user_pref("services.blocklist.pinning.checked", 1549700004);
user_pref("services.blocklist.plugins.checked", 1549700004);
user_pref("services.settings.clock_skew_seconds", -102);
user_pref("services.settings.last_update_seconds", 1549700265);
user_pref("services.settings.main.language-dictionaries.last_check", 1549700004);
user_pref("services.settings.main.onboarding.last_check", 1549700004);
user_pref("services.settings.main.sites-classification.last_check", 1549700004);
user_pref("services.settings.main.tippytop.last_check", 1549700004);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1549700633);
user_pref("toolkit.startup.last_success", 1550205852);
user_pref("toolkit.telemetry.cachedClientID", "8c64eb72-389f-4cce-a497-add2d0b3f96e");
user_pref("toolkit.telemetry.previousBuildID", "20190128144255");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
